/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccelerateProject: typeof import('./components/directory/AccelerateProject.vue')['default']
    Appbar: typeof import('./components/common/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BellNotification: typeof import('./components/common/BellNotification.vue')['default']
    CancelPromptDialog: typeof import('./components/common/CancelPromptDialog.vue')['default']
    CancelPromptDialogCN: typeof import('./components/CancelPromptDialogCN.vue')['default']
    ChatBot: typeof import('./components/common/chatBot.vue')['default']
    DirectoryProjectInfo: typeof import('./components/common/DirectoryProjectInfo.vue')['default']
    DirectoryProjects: typeof import('./components/directory/DirectoryProjects.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ManageProjectView: typeof import('./components/directory/ManageProjectView.vue')['default']
    ModulesDropDown: typeof import('./components/directory/ModulesDropDown.vue')['default']
    ProjectForm: typeof import('./components/directory/ProjectForm.vue')['default']
    ProjectInfoForm: typeof import('./components/directory/ProjectInfoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenState: typeof import('./components/common/ScreenState.vue')['default']
    SetupProjectView: typeof import('./components/directory/SetupProjectView.vue')['default']
    TermsandConditions: typeof import('./components/common/TermsandConditions.vue')['default']
    UserContext: typeof import('./components/common/UserContext.vue')['default']
    ViewerSettings: typeof import('./components/directory/ViewerSettings.vue')['default']
  }
}
